version: '3.8'

# Production deployment note:
# This docker-compose file uses environment variables from the .env file
# Make sure to create a .env file based on .env.example before deployment
# Never commit your actual .env file to version control

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
      args:
        - REPO_URL=${REPO_URL}
        - REPO_BRANCH=${REPO_BRANCH}
    container_name: openwebui-backend
    restart: unless-stopped
    environment:
      - VM_PORT=${VM_PORT}
      - WORKSPACE_DIR=${WORKSPACE_DIR}
      - API_HOST=${API_HOST}
      - API_TIMEOUT=${API_TIMEOUT}
      - ENABLE_AUTH=${ENABLE_AUTH}
      - LOG_LEVEL=${LOG_LEVEL}
    ports:
      - "${VM_PORT}:${VM_PORT}"  # Local port for the backend API
    volumes:
      - workspace_data:${WORKSPACE_DIR}
    networks:
      - openwebui_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${COOLIFY_HEALTHCHECK_PORT}${COOLIFY_HEALTHCHECK_PATH}"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    deploy:
      resources:
        limits:
          memory: ${MEMORY_LIMIT}
          cpus: ${CPU_LIMIT}
    labels:
      coolify.managed: "true"
      coolify.version: "1"
      coolify.type: "app"
      coolify.name: "OpenWebUI Backend"
      coolify.description: "Ubuntu VM environment for OpenWebUI"
      coolify.deployment.strategy: "rolling"
      coolify.healthcheck: "true"
      coolify.healthcheck.path: "${COOLIFY_HEALTHCHECK_PATH}"
      coolify.healthcheck.port: "${COOLIFY_HEALTHCHECK_PORT}"
      coolify.logs: "true"

networks:
  openwebui_network:
    name: openwebui_network
    driver: bridge

volumes:
  workspace_data:
    name: openwebui_workspace 